# -*- coding: utf-8 -*-
"""poev_dashboard_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aA55m-theGfE3jzU9wUrpp9edwUR2xjJ
"""

# Instalação de dependências
!pip install textblob openpyxl
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from textblob import TextBlob
from collections import Counter
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Carregar dados da pesquisa do arquivo em formato Excel.
# IMPORTANTE: Salvar o arquivo com o nome: "dados_pesquisa"
excel_file = 'dados_pesquisa.xlsx'
df = pd.read_excel(excel_file, engine='openpyxl')

# Pré-processamento dos dados e Preparação dos Dados para o Dashboard Unificado

# 1. Distribuição da Satisfação Geral
distribuicao_satisfacao_geral = ['Muito satisfeito', 'Satisfeito', 'Neutro', 'Insatisfeito', 'Muito insatisfeito']
contagem_respostas = [df['Qual é o seu nível geral de satisfação com o site?'].value_counts().get(level, 0) for level in distribuicao_satisfacao_geral]

# 2. Aspectos Avaliados
aspectos_avaliacao = [
    'Suporte/Atendimento',
    'Processo de cadastro',
    'Clareza das informações',
    'Aparência/Design',
    'Velocidade de carregamento',
    'Facilidade de navegação'
]
medias_aspectos = [
    df[aspecto].mean() for aspecto in aspectos_avaliacao
]

# 3. Problemas relatados (Sim/Não)
problemas_identificados = df['Você encontrou algum problema durante sua visita ao site?'].dropna()
problemas_categorizados = problemas_identificados.apply(lambda x: 'Sim' if x != 'Não' else 'Não')
contagem_problemas_relatados = problemas_categorizados.value_counts()
problemas_sim_nao_contagem = contagem_problemas_relatados.filter(items=['Sim', 'Não'])

# 4. Distribuição de Dispositivos
def parse_dispositivos(dispositivos_str):
    if pd.isna(dispositivos_str):
        return []
    return [d.strip() for d in str(dispositivos_str).replace('Computador/Notebook', 'Computador').replace('Celular', 'Celular').replace('Tablet', 'Tablet').split(';') if d.strip()]

todos_dispositivos = []
for entry in df['Qual dispositivo você utilizou para acessar o site?']:
    todos_dispositivos.extend(parse_dispositivos(entry))
lista_dispositivos = ['Tablet', 'Celular', 'Computador']
percentual_uso_dispositivo = [100 * todos_dispositivos.count(dev) / len(df) if len(df) > 0 else 0 for dev in lista_dispositivos]


# 5. Conteúdo Desejado (Preparação para o gráfico)
# Usar o nome exato da coluna
conteudos_desejados_bruto = df['Que tipo de conteúdo você gostaria de ver mais no site?\xa0(ex: tutoriais, vídeos, artigos, comparativos, dicas, novidades, etc.)'].dropna()
conteudos_lista_simples = []
for entry in conteudos_desejados_bruto:
    conteudos_lista_simples.extend([c.strip().capitalize() for c in str(entry).replace('.', '').replace(',', ';').split(';') if c.strip()])
contagem_conteudos_desejados = Counter(conteudos_lista_simples)
# Pegar os 5 mais comuns para o gráfico
lista_conteudos_desejados, numero_solicitacoes_conteudos = zip(*contagem_conteudos_desejados.most_common(5)) if contagem_conteudos_desejados else ([], [])

# 6. Análise de Sentimento
coluna_feedback = 'O que você acha que poderia ser melhorado?'
# Tratar NaNs antes de aplicar TextBlob
df['Sentimento'] = df[coluna_feedback].apply(lambda x: TextBlob(str(x)).sentiment.polarity if pd.notna(x) else np.nan)
df['Sentimento'] = df['Sentimento'].fillna(df['Sentimento'].mean()) # Preencher NaNs após análise de sentimento


# --- Preparação dos Dados para o Dashboard de Machine Learning ---

# Definir variável alvo e features
variavel_alvo = 'Qual é o seu nível geral de satisfação com o site?'
y = df[variavel_alvo]

# Criar uma feature numérica para 'Problemas Relatados'
# 1 se um problema foi relatado ('Sim'), 0 caso contrário ('Não')
df['Problema_Relatado'] = df['Você encontrou algum problema durante sua visita ao site?'].apply(lambda x: 1 if x != 'Não' and pd.notna(x) else 0)

# Criar features numéricas a partir de 'Conteúdo Desejado' usando one-hot encoding
# Isso criará uma nova coluna para cada tipo de conteúdo desejado
# Usar o nome exato da coluna
conteudos_dummies = df['Que tipo de conteúdo você gostaria de ver mais no site?\xa0(ex: tutoriais, vídeos, artigos, comparativos, dicas, novidades, etc.)'].str.get_dummies(sep=';')

# Limpar nomes das colunas do one-hot encoding (remover espaços iniciais/finais e caracteres especiais)
conteudos_dummies.columns = [col.strip().replace('\xa0', '').replace('.', '').replace('(', '').replace(')', '') for col in conteudos_dummies.columns]

# Drop any columns that might be empty or represent unwanted responses like '-' or '.'
conteudos_dummies = conteudos_dummies.drop(columns=['-', ''], errors='ignore')

# Concatenar o DataFrame original com as features one-hot encoded
# Usando axis=1 para adicionar colunas
df_ml = pd.concat([df, conteudos_dummies], axis=1)


# Definir as features (incluir avaliações de aspectos, features engenheiradas e colunas one-hot encoded)
# Obter os nomes limpos das colunas de conteudos_dummies
cleaned_conteudos_cols = list(conteudos_dummies.columns)

# Combinar todas as colunas de features
colunas_features = aspectos_avaliacao + ['Sentimento', 'Problema_Relatado'] + cleaned_conteudos_cols
X = df_ml[colunas_features]


# Converter a variável alvo para rótulos numéricos
label_encoder = LabelEncoder()
# Lidar com valores ausentes em y antes de fit_transform
y_encoded = label_encoder.fit_transform(y.astype(str)) # Converter para string para lidar com NaNs se houver


# Lidar com valores ausentes nas features
# Preencher NaNs em X após defini-lo
X = X.fillna(X.mean())

# Dividir os dados (necessário para o LabelEncoder e para simular o fluxo, embora o modelo final não seja treinado aqui)
# Para o dashboard, usaremos os dados completos para feature importance, mas a divisão é boa prática.
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Selecionar e treinar o modelo (treinar no conjunto completo para feature importance no dashboard)
model = LogisticRegression(max_iter=1000)
model.fit(X, y_encoded) # Treinar no conjunto completo para feature importance

# Obter Importância das Features
coefficients = model.coef_[0]
feature_names = X.columns
importancia_features = pd.DataFrame({'Feature': feature_names, 'Coefficient': coefficients})
importancia_features['Abs_Coefficient'] = abs(importancia_features['Coefficient'])
importancia_features = importancia_features.sort_values(by='Abs_Coefficient', ascending=False)


# Dashboard Unificado

# Criar uma nova figura com subplots para o dashboard unificado
figura_dashboard, eixos_dashboard = plt.subplots(3, 2, figsize=(15, 18)) # 3 linhas e 2 colunas

# Adicionar Gráfico 1 das Estatísticas Simples: Distribuição de Satisfação (Gráfico de Pizza)
eixos_dashboard[0][0].pie(contagem_respostas, labels=distribuicao_satisfacao_geral, autopct='%1.1f%%', colors=['skyblue', 'lightgreen', 'lightgray', 'salmon', 'lightcoral'])
eixos_dashboard[0][0].set_title('Distribuição da Satisfação Geral')

# Adicionar Gráfico 2 das Estatísticas Simples: Avaliações de Aspectos (Gráfico de Barras)
eixos_dashboard[0][1].barh(aspectos_avaliacao, medias_aspectos, color='lightgreen')
eixos_dashboard[0][1].set_title('Notas Médias por Aspecto Avaliado')
eixos_dashboard[0][1].set_xlabel('Nota Média')

# Adicionar Gráfico 3 das Estatísticas Simples: Problemas Relatados (Gráfico de Pizza - Apenas Sim/Não)
problemas_sim_nao_contagem = contagem_problemas_relatados.filter(items=['Sim', 'Não'])
eixos_dashboard[1][0].pie(problemas_sim_nao_contagem.values, labels=problemas_sim_nao_contagem.index, autopct='%1.1f%%', colors=['salmon', 'lightgray'])
eixos_dashboard[1][0].set_title('Problemas Relatados (Sim/Não)')

# Adicionar Gráfico 4 das Estatísticas Simples: Distribuição de Dispositivos (Gráfico de Pizza)
eixos_dashboard[1][1].pie(percentual_uso_dispositivo, labels=lista_dispositivos, autopct='%1.1f%%', colors=['gold', 'lightcoral', 'lightskyblue'])
eixos_dashboard[1][1].set_title('Distribuição por Dispositivo')

# Adicionar Gráfico 1 de Machine Learning: Plot de Importância de Features (Gráfico de Barras)
# Ordenar as features pela importância (valor absoluto do coeficiente) e selecionar as top N
top_n_features = 10 # Define o número de features a serem exibidas para limitar o número de categorias no gráfico
importancia_features_top = importancia_features.head(top_n_features)

eixos_dashboard[2][0].bar(importancia_features_top['Feature'], importancia_features_top['Abs_Coefficient'], color='teal')
eixos_dashboard[2][0].set_title(f'Top {top_n_features} Features Mais Importantes (Valor Absoluto do Coeficiente)')
eixos_dashboard[2][0].set_xlabel('Feature')
eixos_dashboard[2][0].set_ylabel('Valor Absoluto do Coeficiente')
eixos_dashboard[2][0].tick_params(axis='x', rotation=90)
eixos_dashboard[2][0].grid(axis='y', linestyle='--', alpha=0.7) # Adicionar grid para facilitar a leitura


# Adicionar Gráfico 2 de Machine Learning: Histograma de Análise de Sentimento
df_ml['Sentimento'].hist(bins=20, color='skyblue', ax=eixos_dashboard[2][1])
eixos_dashboard[2][1].set_title('Distribuição do Sentimento nas Respostas')
eixos_dashboard[2][1].set_xlabel('Polaridade do Sentimento')
eixos_dashboard[2][1].set_ylabel('Frequência')


plt.tight_layout()
plt.show()
