# Generated by Django 5.2.7 on 2025-11-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoevFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfacao_geral', models.CharField(choices=[('MT_SAT', 'Muito satisfeito'), ('SAT', 'Satisfeito'), ('NEUTRO', 'Neutro'), ('INSAT', 'Insatisfeito'), ('MT_INSAT', 'Muito insatisfeito')], max_length=12)),
                ('nota_usabilidade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nota_navegacao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nota_performance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nota_design', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nota_conteudo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nota_busca_vagas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nota_acessibilidade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('teve_problema', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('problema_outro', models.CharField(blank=True, max_length=300)),
                ('mais_gostou', models.TextField(blank=True)),
                ('melhorar', models.TextField(blank=True)),
                ('nps', models.PositiveSmallIntegerField()),
                ('conteudo_atendeu', models.CharField(choices=[('SIM', 'Sim'), ('PARCIAL', 'Parcialmente'), ('NAO', 'Não'), ('NS', 'Não tenho certeza')], max_length=10)),
                ('conteudo_util', models.CharField(choices=[('SIM', 'Sim'), ('PARTE', 'Em parte'), ('NAO', 'Não')], max_length=10)),
                ('linguagem_clara', models.CharField(choices=[('CLARA', 'Sim, foi muito clara'), ('OK', 'Sim, mas poderia ser um pouco mais simples'), ('CONFUSA', 'Não, achei confusa'), ('NA', 'Não se aplica')], max_length=8)),
                ('nivel_detalhe', models.CharField(choices=[('ADEQ', 'Sim, a profundidade foi suficiente'), ('FALTOU', 'Não, faltaram detalhes'), ('EXCESSO', 'Não, havia informação em excesso'), ('NA', 'Não se aplica')], max_length=8)),
                ('encontrou_erros', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('erros_outros', models.CharField(blank=True, max_length=300)),
                ('conteudo_desejado', models.TextField(blank=True)),
                ('nota_atualizacao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area_desatualizada', models.CharField(blank=True, max_length=200)),
                ('dispositivo', models.CharField(choices=[('DESKTOP', 'Computador/Notebook'), ('MOBILE', 'Celular'), ('TABLET', 'Tablet')], max_length=8)),
                ('otimizado_para_dispositivo', models.CharField(choices=[('TOTAL', 'Sim, totalmente'), ('PARCIAL', 'Parcialmente'), ('NAO', 'Não')], max_length=8)),
                ('funcionalidade_desejada', models.TextField(blank=True)),
                ('como_conheceu', models.CharField(choices=[('GOOGLE', 'Google/Pesquisa online'), ('SOCIAL', 'Redes sociais'), ('INDICACAO', 'Indicação de amigos/colegas'), ('OUTROS', 'Outros')], max_length=10)),
                ('quer_receber_atualizacoes', models.BooleanField(default=False)),
                ('nome_contato', models.CharField(blank=True, max_length=120)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_contato', models.CharField(blank=True, max_length=30)),
                ('consentimento_contato', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback POEV',
                'verbose_name_plural': 'Feedbacks POEV',
                'ordering': ['-created_at'],
            },
        ),
    ]
