# Generated by Django 5.2.7 on 2025-11-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_anuncianteprofile_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoprofile',
            name='instituicao',
            field=models.CharField(choices=[('', 'Selecione sua Instituição'), ('UNIVESP', 'Univesp'), ('OUTRA', 'Outra Instituição')], max_length=100),
        ),
    ]
